### ISSUE TITLE
Build issue with ESP IDF on Rasperry 4B

### ISSUE THREAD

**Issue by killamilla0815** [limpens/SolarEdge#1]
Hello

I am getting errors, when trying to compile the project on a default RasperryPi 4b and also Windows ESP IDF environment, please see the outputs below.

Any chance to provide the final .bin file for ESP32 in order to overcome such build issues ?

Cheers.

**"idf.py build" output on Rasperry 4B:**
 
...
In file included from ../main/espWifi.cpp:14:
/home/pi/esp/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:10:74: note: '#pragma message: esp_wpa2.h is deprecated. Use esp_eap_client.h instead.'
   10 | #pragma message("esp_wpa2.h is deprecated. Use esp_eap_client.h instead.")
      |                                                                          ^
/home/pi/esp/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:327:1: error: expected declaration before '}' token
  327 | }
      | ^
In file included from /home/pi/esp/esp-idf/components/esp_hw_support/include/esp_intr_alloc.h:12,
                 from /home/pi/esp/esp-idf/components/esp_hw_support/include/esp_cpu.h:20,
                 from /home/pi/esp/esp-idf/components/esp_hw_support/include/spinlock.h:11,
                 from /home/pi/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:49,
                 from /home/pi/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include/freertos/portable.h:57,
                 from /home/pi/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include/freertos/FreeRTOS.h:69,
                 from /home/pi/esp/esp-idf/components/esp_system/include/esp_task.h:24,
                 from /home/pi/esp/esp-idf/components/lwip/port/include/lwipopts.h:20,
                 from /home/pi/esp/esp-idf/components/lwip/lwip/src/include/lwip/opt.h:51,
                 from /home/pi/esp/esp-idf/components/lwip/lwip/src/include/lwip/sockets.h:42,
                 from /home/pi/esp/esp-idf/components/lwip/include/lwip/sockets.h:8,
                 from /home/pi/esp/esp-idf/components/lwip/port/esp32xx/include/sys/socket.h:15,
                 from ../main/espWifi.cpp:2:
../main/espWifi.cpp: In member function 'esp_err_t espWifi::Up()':
../main/espWifi.cpp:182:83: warning: 'esp_err_t esp_wifi_sta_wpa2_ent_set_identity(const unsigned char*, int)' is deprecated: Use 'esp_eap_client_set_identity' instead [-Wdeprecated-declarations]
  182 |                                 ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_set_identity((unsigned char *)auth.identity, strlen(auth.identity)));
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/esp/esp-idf/components/esp_common/include/esp_err.h:116:30: note: in definition of macro 'ESP_ERROR_CHECK'
  116 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
/home/pi/esp/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:62:11: note: declared here
   62 | esp_err_t esp_wifi_sta_wpa2_ent_set_identity(const unsigned char *identity, int len);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../main/espWifi.cpp:183:83: warning: 'esp_err_t esp_wifi_sta_wpa2_ent_set_username(const unsigned char*, int)' is deprecated: Use 'esp_eap_client_set_username' instead [-Wdeprecated-declarations]
  183 |                                 ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_set_username((unsigned char *)auth.username, strlen(auth.username)));
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/esp/esp-idf/components/esp_common/include/esp_err.h:116:30: note: in definition of macro 'ESP_ERROR_CHECK'
  116 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
/home/pi/esp/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:89:11: note: declared here
   89 | esp_err_t esp_wifi_sta_wpa2_ent_set_username(const unsigned char *username, int len);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../main/espWifi.cpp:184:83: warning: 'esp_err_t esp_wifi_sta_wpa2_ent_set_password(const unsigned char*, int)' is deprecated: Use 'esp_eap_client_set_password' instead [-Wdeprecated-declarations]
  184 |                                 ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_set_password((unsigned char *)auth.password, strlen(auth.password)));
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/esp/esp-idf/components/esp_common/include/esp_err.h:116:30: note: in definition of macro 'ESP_ERROR_CHECK'
  116 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
/home/pi/esp/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:115:11: note: declared here
  115 | esp_err_t esp_wifi_sta_wpa2_ent_set_password(const unsigned char *password, int len);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../main/espWifi.cpp:185:77: warning: 'esp_err_t esp_wifi_sta_wpa2_ent_enable()' is deprecated: Use 'esp_wifi_sta_enterprise_enable' instead [-Wdeprecated-declarations]
  185 |                                 ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_enable());
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/pi/esp/esp-idf/components/esp_common/include/esp_err.h:116:30: note: in definition of macro 'ESP_ERROR_CHECK'
  116 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
/home/pi/esp/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:28:11: note: declared here
   28 | esp_err_t esp_wifi_sta_wpa2_ent_enable(void);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[953/962] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/modbus.cpp.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /home/pi/esp/SolarEdge/build/log/idf_py_stderr_output_23421 and /home/pi/esp/SolarEdge/build/log/idf_py_stdout_output_23421

**"idf.py build" output on Windows:**

C:/Espressif/frameworks/SolarEdge-main/main/espWifi.cpp: In member function 'esp_err_t espWifi::Up()':
C:/Espressif/frameworks/SolarEdge-main/main/espWifi.cpp:182:83: warning: 'esp_err_t esp_wifi_sta_wpa2_ent_set_identity(const unsigned char*, int)' is deprecated: Use 'esp_eap_client_set_identity' instead [-Wdeprecated-declarations]
  182 |                                 ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_set_identity((unsigned char *)auth.identity, strlen(auth.identity)));
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Espressif/frameworks/esp-idf-v5.2.1/components/esp_common/include/esp_err.h:117:30: note: in definition of macro 'ESP_ERROR_CHECK'
  117 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
C:/Espressif/frameworks/esp-idf-v5.2.1/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:62:11: note: declared here
   62 | esp_err_t esp_wifi_sta_wpa2_ent_set_identity(const unsigned char *identity, int len);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Espressif/frameworks/SolarEdge-main/main/espWifi.cpp:183:83: warning: 'esp_err_t esp_wifi_sta_wpa2_ent_set_username(const unsigned char*, int)' is deprecated: Use 'esp_eap_client_set_username' instead [-Wdeprecated-declarations]
  183 |                                 ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_set_username((unsigned char *)auth.username, strlen(auth.username)));
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Espressif/frameworks/esp-idf-v5.2.1/components/esp_common/include/esp_err.h:117:30: note: in definition of macro 'ESP_ERROR_CHECK'
  117 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
C:/Espressif/frameworks/esp-idf-v5.2.1/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:89:11: note: declared here
   89 | esp_err_t esp_wifi_sta_wpa2_ent_set_username(const unsigned char *username, int len);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Espressif/frameworks/SolarEdge-main/main/espWifi.cpp:184:83: warning: 'esp_err_t esp_wifi_sta_wpa2_ent_set_password(const unsigned char*, int)' is deprecated: Use 'esp_eap_client_set_password' instead [-Wdeprecated-declarations]
  184 |                                 ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_set_password((unsigned char *)auth.password, strlen(auth.password)));
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Espressif/frameworks/esp-idf-v5.2.1/components/esp_common/include/esp_err.h:117:30: note: in definition of macro 'ESP_ERROR_CHECK'
  117 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
C:/Espressif/frameworks/esp-idf-v5.2.1/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:115:11: note: declared here
  115 | esp_err_t esp_wifi_sta_wpa2_ent_set_password(const unsigned char *password, int len);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Espressif/frameworks/SolarEdge-main/main/espWifi.cpp:185:77: warning: 'esp_err_t esp_wifi_sta_wpa2_ent_enable()' is deprecated: Use 'esp_wifi_sta_enterprise_enable' instead [-Wdeprecated-declarations]
  185 |                                 ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_enable());
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
C:/Espressif/frameworks/esp-idf-v5.2.1/components/esp_common/include/esp_err.h:117:30: note: in definition of macro 'ESP_ERROR_CHECK'
  117 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
C:/Espressif/frameworks/esp-idf-v5.2.1/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:28:11: note: declared here
   28 | esp_err_t esp_wifi_sta_wpa2_ent_enable(void);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[920/926] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/modbus.cpp.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the C:\Espressif\frameworks\SolarEdge-main\build\log\idf_py_stderr_output_7844 and C:\Espressif\frameworks\SolarEdge-main\build\log\idf_py_stdout_output_7844

**Comment by limpens** [comment]
Modified the code to use the new WPA2 calls.

**Comment by killamilla0815** [comment]
Very cool, thanks a lot for your quick interaction, mate ! 

Will check later today if the build process will run through. THX.
